server:
  port: 2000

  error:
    include-message: always

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/admin

  mail:
    host: smtp.gmail.com
    port: 587
    username: dharjeezy@gmail.com
    password: password
    test-connection: false

logging:
  file:
    name: flexisaf.log
