server:
  port: 2000

  error:
    include-message: always

spring:
  data:
    mongodb:
      uri: mongodb://root:password@127.0.0.1:27017/kudi

  mail:
    host: smtp.gmail.com
    port: 587
    username: dharjeezy@gmail.com
    password: sowrong
    test-connection: false

logging:
  file:
    name: flexisaf.log
